# (name, locality/office area, hub zone, sector, confidence, source)
# Confidence: MED = named in a curated/industry list or directory with a locality; LOW = named in a list without a locality
N = [
# --- Andheri / SEEPZ / Marol / Jogeshwari
("IBM India","Andheri East","Andheri/SEEPZ","MNC IT services, cloud, AI","MED","mygate.com; buzz4ai.com"),
("Orient Technologies Ltd","Andheri East (head office)","Andheri/SEEPZ","IT infrastructure, cloud, managed services","MED","justdial.com; asklaila.com"),
("Net Business Solutions India Ltd","Andheri East","Andheri/SEEPZ","IT services","MED","justdial.com"),
("Immortal Computer Lab Pvt Ltd","Marol","Andheri/SEEPZ","Software services","MED","asklaila.com"),
("Systems International","Jogeshwari East","Andheri/SEEPZ","IT services","MED","asklaila.com"),
("Innovia Software","Mumbai","Andheri/SEEPZ","CRM and ERP solutions","LOW","buzz4ai.com"),
("Intertec Software Pvt Ltd","Mumbai","Andheri/SEEPZ","Software products","LOW","buzz4ai.com"),
("Traffic Tail","Mumbai","Andheri/SEEPZ","Digital/web services","LOW","buzz4ai.com"),
("Mugenesys","Mumbai","Andheri/SEEPZ","Software development","LOW","mugenesys.com"),
("Mastercard","Andheri East (loyalty solutions centre) + Bandra East (India HQ)","BKC/Andheri","Payments technology","MED","builtinmumbai.in"),
# --- BKC
("Google India","Fortune 2000, Bandra Kurla Complex","BKC","Product engineering, cloud, ads tech","MED","internshala.com blog"),
("Dynatrace India Software Operations Pvt Ltd","20th Floor, Parinee Crescenzo, G Block BKC, Bandra East","BKC","Observability/APM software product","MED","dynatrace.com/careers"),
("Morningstar India","Mumbai","BKC","Investment data, research, analytics software","MED","builtinmumbai.in"),
# --- Powai
("Tata Consultancy Services (TCS)","Powai + Thane (Hiranandani Estate)","Powai/Thane","IT services, consulting","MED","brandveda.in; internshala.com"),
("SpeEdLabs","Powai","Powai","EdTech - adaptive learning platform","MED","indeed.in listing"),
("Infosys Ltd","Powai (reported)","Powai","IT services","LOW","sulekha.com; quora"),
# --- Thane
("Silgate Solutions Ltd","808 B Wing, Ashar IT Park, Wagle Estate, Thane","Thane","IT services","MED","indiaonline.in"),
("Balaji Infotech","9th Floor, Rd 16A, Wagle Industrial Estate, Thane West","Thane","IT services","MED","indiaonline.in"),
# --- Product / consumer tech
("Dream11","Mumbai","Mumbai (product)","Fantasy sports platform, large-scale backend","MED","internshala.com blog"),
("BookMyShow","Mumbai","Mumbai (product)","Ticketing platform, backend and mobile","MED","internshala.com blog"),
("BrowserStack","Mumbai","Mumbai (product)","Developer tools SaaS - cross-browser testing","MED","internshala.com blog"),
("Rebel Foods","Mumbai","Mumbai (product)","Cloud-kitchen platform technology","MED","failory.com"),
("Persistent Systems","Mumbai","Mumbai (services)","Product engineering, cloud, IoT","MED","softlabsgroup.com"),
("Zepto","Mumbai","Mumbai (product)","Quick-commerce platform","MED","startupblink.com"),
("Games24x7","Mumbai (HQ)","Mumbai (product)","Online gaming - RummyCircle, My11Circle","MED","en.wikipedia.org"),
("Viacom18 Media Pvt Ltd","Mumbai (HQ)","Mumbai (media tech)","Media streaming and broadcast technology","MED","builtinmumbai.in"),
("GroupM India","Mumbai","Mumbai (media tech)","Media investment, adtech platforms","MED","builtinmumbai.in"),
# --- FinTech
("InCred","Mumbai","Mumbai (fintech)","Lending platform, data science","MED","inc42.com; beststartup.in"),
("Mintifi","Mumbai","Mumbai (fintech)","Supply-chain financing platform","MED","inc42.com"),
("Weaver (Weaver Services)","Mumbai","Mumbai (fintech)","Financial services technology","MED","inc42.com"),
("Piramal Capital & Housing Finance","Mumbai","Mumbai (fintech)","Lending technology platforms","MED","inc42.com"),
("Vastu Housing Finance","Mumbai","Mumbai (fintech)","Housing finance technology","MED","inc42.com"),
("Drip Capital","Mumbai","Mumbai (fintech)","Trade finance platform","MED","inc42.com"),
("BillDesk","Mumbai","Mumbai (fintech)","Payment gateway and bill payments","MED","inc42.com"),
("CoinDCX","Mumbai","Mumbai (fintech)","Crypto exchange platform","MED","inc42.com"),
("Angel One","Mumbai","Mumbai (fintech)","Broking platform, trading technology","MED","inc42.com"),
("Jupiter (Amica Financial)","Mumbai","Mumbai (fintech)","Neobanking app","MED","beststartup.in; failory.com"),
("Upstox (RKSV Securities)","Mumbai (HQ)","Mumbai (fintech)","Online stock trading platform","MED","inc42.com"),
("Turtlemint","Mumbai","Mumbai (insurtech)","Insurance distribution platform","MED","tracxn.com; inc42.com"),
("Eduvanz Financing","Mumbai","Mumbai (fintech)","Education lending NBFC, digital underwriting","MED","beststartup.in"),
("CASHe (Aeries Financial Technologies)","Mumbai","Mumbai (fintech)","App-based personal lending","MED","beststartup.in"),
("Kuhoo Finance","Mumbai","Mumbai (fintech)","Digital student loans","MED","beststartup.in"),
("Kissht (OnEMi Technology Solutions)","Mumbai","Mumbai (fintech)","Consumer credit platform","MED","beststartup.in"),
("Mswipe Technologies","Mumbai","Mumbai (fintech)","POS payment hardware and software","MED","beststartup.in"),
("Citrus Pay","Mumbai","Mumbai (fintech)","Payment gateway, digital wallet","LOW","beststartup.in"),
("IDfy (Baldor Technologies)","Mumbai","Mumbai (fintech)","Identity verification, fraud detection, ML","MED","beststartup.in; tracxn.com"),
("Avenues India Pvt Ltd (CCAvenue)","Mumbai","Mumbai (fintech)","Payment gateway, remittance IT","MED","beststartup.in"),
("Acko General Insurance","Mumbai","Mumbai (insurtech)","Digital insurance platform","MED","registerkaro.in"),
("FlexiLoans","Mumbai","Mumbai (fintech)","SME lending SaaS platform","MED","tracxn.com"),
("Karza Technologies","Lower Parel","Lower Parel/Worli","Due diligence, financial analytics, banking APIs","MED","grotal.com; asklaila.com"),
("CreditWise Capital","Mumbai","Mumbai (fintech)","Lending technology","MED","tracxn.com"),
("Riskcovry","Mumbai","Mumbai (insurtech)","Insurance infrastructure SaaS","MED","tracxn.com"),
("OneAssist Consumer Solutions","Mumbai","Mumbai (insurtech)","Device and card protection platform","MED","tracxn.com"),
# --- SaaS / B2B product
("Seclore Technology","Mumbai","Mumbai (SaaS)","Data-centric security, rights management","MED","tracxn.com"),
("Flipspaces","Mumbai","Mumbai (SaaS)","Design-tech / VR for interiors","MED","tracxn.com"),
("Freight Tiger","Mumbai","Mumbai (SaaS)","Digital freight management platform","MED","tracxn.com"),
("ZingHR","Mumbai","Mumbai (SaaS)","HR-tech SaaS platform","MED","tracxn.com"),
("Mozark","Mumbai","Mumbai (SaaS)","App experience and network testing SaaS","MED","tracxn.com"),
("Intelligence Node","Mumbai","Mumbai (SaaS)","Retail analytics, price intelligence","MED","tracxn.com"),
("Peel-Works","Mumbai","Mumbai (SaaS)","Retail distribution SaaS","MED","tracxn.com"),
("BlueOptima","Mumbai","Mumbai (SaaS)","Developer productivity analytics SaaS","MED","tracxn.com"),
("Leadzen","Mumbai","Mumbai (SaaS)","B2B lead-generation SaaS, AI","MED","wellfound.com"),
("InspireOne Technologies (Master-O)","Mumbai","Mumbai (SaaS)","B2B sales-enablement SaaS","MED","cutshort.io"),
("Neysa Networks","Mumbai","Mumbai (cloud/AI)","AI cloud, GPU compute platform","MED","analyticsinsight.net"),
# --- AI / ML / analytics
("Fractal Analytics","Mumbai","Mumbai (AI)","AI and advanced analytics","MED","guvi.in"),
("LogiNext Solutions","Mumbai","Mumbai (SaaS)","Logistics optimisation SaaS","MED","guvi.in; clickpost.ai"),
("Haptik Technologies","Mumbai","Mumbai (AI)","Conversational AI, chatbots","MED","guvi.in"),
("Qure.ai","Mumbai","Mumbai (AI)","Medical imaging AI, deep learning","MED","guvi.in"),
("Datamatics Global Services","Mumbai","Mumbai (AI)","RPA, AI BI, data analytics (TruBot, TruBI)","MED","guvi.in"),
("Miko (Miko Technologies)","Mumbai","Mumbai (AI)","Consumer robotics, conversational AI","MED","guvi.in; tracxn.com"),
("HyperVerge","Mumbai","Mumbai (AI)","AI for identity verification, computer vision","MED","guvi.in"),
("Wright Research","Mumbai","Mumbai (AI)","AI-driven investment research","MED","tracxn.com"),
("Bull AI","Mumbai","Mumbai (AI)","AI for investment tech","LOW","tracxn.com"),
("Intellimation","Mumbai","Mumbai (AI)","AI and automation for BFSI","LOW","tracxn.com"),
("Novaex","Mumbai","Mumbai (AI)","AI investment tech","LOW","tracxn.com"),
("FidelFolio Investments","Mumbai","Mumbai (AI)","AI-driven equity research","LOW","tracxn.com"),
("Arya.ai","Mumbai","Mumbai (AI)","AI cloud platform for banks and insurers","MED","builtinmumbai.in; tracxn.com"),
("Navsoft","Mumbai","Mumbai (AI)","AI, IT services","MED","clutch.co; themanifest.com"),
("Matrix Bricks Infotech","Mumbai","Mumbai (AI)","AI, web and digital services","MED","clutch.co"),
("Agram Konnect","Mumbai","Mumbai (AI)","AI and software development","LOW","clutch.co"),
("Perimattic","Mumbai","Mumbai (AI)","AI and software engineering","LOW","clutch.co"),
("Indigloo Softwares Pvt Ltd","Mumbai","Mumbai (AI)","AI and software development","LOW","clutch.co"),
("April Innovations","Mumbai","Mumbai (AI)","AI and software development","LOW","clutch.co"),
("QED42","Mumbai","Mumbai (web/AI)","Drupal, web engineering, AI","MED","clutch.co"),
("Unico Connect","Mumbai","Mumbai (web)","Full-stack web and mobile development","MED","goodfirms.co (4.8 stars, 43 reviews)"),
("Ajackus","Mumbai","Mumbai (web)","Full-stack engineering, AI","MED","clutch.co"),
("Bombay Softwares","Mumbai","Mumbai (web)","Software and web development","MED","clutch.co"),
# --- Web / app agencies
("3minds Digital","Mumbai","Mumbai (web)","Web and app development, design","MED","clutch.co"),
("SIB Infotech","Mumbai","Mumbai (web)","Web development, SEO","MED","clutch.co"),
("Inboundsys","Mumbai","Mumbai (web)","Web development, HubSpot/CMS","LOW","clutch.co"),
("Zoot Digital","Mumbai","Mumbai (web)","Digital marketing and web","LOW","clutch.co"),
("Robosoft Technologies","Mumbai","Mumbai (web)","App and product engineering","MED","clutch.co"),
("Azul Arc","Mumbai","Mumbai (web)","Web and app development","LOW","clutch.co"),
("Buzzlink Studios","Mumbai","Mumbai (web)","Website, ecommerce, app development, SEO","MED","mumbaiwebdesign.in"),
("Probey Services","Mumbai (India branch)","Mumbai (web)","App and web development","MED","goodfirms.co"),
("Promatics Technologies","Mumbai","Mumbai (web)","Mobile app development, UI/UX","MED","goodfirms.co"),
("Furation Tech Solutions","Mumbai","Mumbai (web)","ISO 9001:2015 IT solutions, app development","MED","goodfirms.co (founded 2018)"),
("Dynamic Vishva","Mumbai","Mumbai (web)","Mobility and software solutions","MED","goodfirms.co"),
("Appic Mobile","Mumbai","Mumbai (web)","Mobile app development","MED","goodfirms.co (founded 2011)"),
("Web Crafters IT Solutions","Swastik Onyx, Vikhroli","Vikhroli/Chembur","Web development, SEO, digital marketing","MED","webcraftersitsolutions.com"),
("Software Smiths","Karma Stambh, C Wing, LBS Marg, Vikhroli West","Vikhroli/Chembur","Software development (since 1989)","MED","asklaila.com"),
("Cloudesign Technology Solutions LLP","Vikhroli West","Vikhroli/Chembur","Android app, web development, networking","MED","techbehemoths.com"),
("Ozias Media Pvt Ltd","Vikhroli","Vikhroli/Chembur","Digital marketing, SEO, branding","LOW","asklaila.com"),
("Dezigndia Technologies","Borivali East","Borivali/Kandivali","IT outsourcing","MED","lexifo.com"),
("eBuild Softwares and Solutions","Office 6A, Trade World D Wing, Kamala Mills, Lower Parel West","Lower Parel/Worli","App development, ERP software","MED","sulekha.com"),
("Hoarway Technology","Lower Parel","Lower Parel/Worli","Software, mobile app, digital marketing","MED","asklaila.com"),
("Trionova","Mumbai","Mumbai (web)","Mobile app development","LOW","trionova.in"),
# --- Cybersecurity
("CyberNX Technologies Pvt Ltd","Mumbai","Mumbai (security)","End-to-end cybersecurity services, SOC","MED","designrush.com; petadot.com"),
("Inspira Enterprise India Ltd","Mumbai","Mumbai (security)","Cybersecurity, data analytics, AI services","MED","designrush.com"),
("CiELO Technologies","Mumbai","Mumbai (security)","Cloud security (founded 2015)","MED","petadot.com"),
("Petadot System & Security Pvt Ltd","Mumbai","Mumbai (security)","Cybersecurity services","MED","petadot.com"),
("IARM Information Security","Mumbai","Mumbai (security)","Information, network and managed security","MED","themanifest.com"),
("Microscan Communications Pvt Ltd","Mumbai","Mumbai (security)","Networking, cloud, cybersecurity managed services","MED","petadot.com"),
("Logix Infosecurity","Mumbai","Mumbai (security)","Email security, compliance","MED","aipeakflow.com"),
("Vista InfoSec","Mumbai","Mumbai (security)","Security audits, compliance (PCI DSS, ISO)","MED","aipeakflow.com"),
# --- Data / analytics / IT services
("Decimal Point Analytics","Mumbai","Mumbai (analytics)","Financial data analytics, research automation","MED","guvi.in"),
("Polestar Analytics","Mumbai","Mumbai (analytics)","Data engineering and analytics consulting","MED","themanifest.com"),
("Cymetrix Software","Mumbai","Mumbai (analytics)","Salesforce, data and cloud consulting","MED","themanifest.com"),
("Umbrella Infocare","Mumbai","Mumbai (cloud)","AWS cloud consulting and DevOps","MED","themanifest.com"),
("Indus Net Technologies Ltd","Mumbai","Mumbai (services)","Full-stack digital engineering","MED","themanifest.com"),
("Accely","Mumbai","Mumbai (services)","SAP consulting and implementation","MED","themanifest.com"),
("Tirnav Solutions Pvt Ltd","Mumbai","Mumbai (services)","IT services and software","MED","themanifest.com"),
("Direction Software LLP","Mumbai","Mumbai (services)","Software development, ERP","MED","themanifest.com"),
("Microland Ltd","Lower Parel","Lower Parel/Worli","IT infrastructure and cloud managed services","MED","grotal.com"),
("NSDL Database Management Ltd","Lower Parel","Lower Parel/Worli","Financial data systems","MED","grotal.com"),
("Genovate Solutions India Pvt Ltd","Lower Parel","Lower Parel/Worli","IT services","MED","grotal.com"),
("Datacraft India Ltd","Lower Parel","Lower Parel/Worli","Network and IT integration","MED","grotal.com"),
("Kalpataru Technologies","Borivali West","Borivali/Kandivali","IT services","MED","asklaila.com"),
("Jagnil Computer And Software","Borivali West","Borivali/Kandivali","Software services","LOW","asklaila.com"),
("CSoft","Borivali West","Borivali/Kandivali","Software services","LOW","asklaila.com"),
("Tejora","Mindspace Malad","Goregaon/Malad","IT and BPO services","MED","getsethome.com"),
("Infinitrix","Mindspace Malad","Goregaon/Malad","IT services","LOW","getsethome.com"),
# --- EdTech
("upGrad","Mumbai","Mumbai (edtech)","Higher-ed platform engineering","MED","tracxn.com"),
("Eruditus Executive Education","Mumbai","Mumbai (edtech)","Executive education platform","MED","tracxn.com"),
("LEAD School (LEAD)","Mumbai","Mumbai (edtech)","School edtech platform","MED","failory.com; tracxn.com"),
("Avanti Learning Centres","Mumbai","Mumbai (edtech)","EdTech platform","MED","tracxn.com"),
("Testbook","Mumbai (HQ)","Mumbai (edtech)","Exam-prep platform, backend and mobile","MED","en.wikipedia.org"),
("IIDE Education Pvt Ltd","Mumbai","Mumbai (edtech)","Digital marketing education; active intern hirer","MED","internshala.com"),
# --- HealthTech
("PharmEasy (API Holdings)","Mumbai","Mumbai (healthtech)","E-pharmacy platform engineering","MED","inc42.com"),
("Medikabazaar","Mumbai","Mumbai (healthtech)","B2B medical supplies marketplace","MED","inc42.com"),
("Truemeds (Intellihealth)","Mumbai","Mumbai (healthtech)","Online pharmacy platform","MED","inc42.com"),
("Zeno Health","Mumbai","Mumbai (healthtech)","Generic pharmacy platform","MED","digitalhealthnews.com"),
("Neodocs","Mumbai","Mumbai (healthtech)","At-home diagnostics, smartphone imaging","MED","digitalhealthnews.com"),
("Wellthy Therapeutics","Mumbai","Mumbai (healthtech)","Digital therapeutics","MED","digitalhealthnews.com"),
("Ivory (Ivory Health)","Mumbai","Mumbai (healthtech)","Neuroscience-backed cognitive assessments","MED","cutshort.io"),
# --- Logistics tech
("GreenLine","Mumbai","Mumbai (logistics)","Logistics technology","MED","tracxn.com"),
("Borzo India","Mumbai","Mumbai (logistics)","On-demand delivery platform","MED","tracxn.com"),
("Oorjaa","Mumbai","Mumbai (logistics)","Technology-driven logistics","MED","tracxn.com"),
("ShipWaves","Mumbai","Mumbai (logistics)","Digital freight forwarding","MED","tracxn.com"),
("iThink Logistics","Mumbai","Mumbai (logistics)","E-commerce shipping aggregator","MED","clickpost.ai"),
# --- ERP / SAP partners
("Uneecops Technologies","Mumbai","Mumbai (ERP)","SAP Business One partner, CMMI Level 5","MED","uneecops.com"),
("Cogniscient Business Solutions","Mumbai","Mumbai (ERP)","SAP Business One partner","MED","cogniscient.in"),
("Atlas Technosoft Pvt Ltd","Mumbai","Mumbai (ERP)","SAP channel partner, ERP implementation","MED","softwaresuggest.com"),
("eNoah iSolution India","Mumbai","Mumbai (ERP)","SAP Business One implementation, ISO 27001","MED","enoahisolution.com"),
("Accelon Tech","Mumbai","Mumbai (ERP)","SAP Business One gold partner","MED","accelontech.com"),
("PTS Systems & Solutions","Mumbai","Mumbai (ERP)","SAP partner, digital transformation","MED","ptssystems.co.in"),
("Cinntra Infotech","Mumbai","Mumbai (ERP)","SAP Business One partner","MED","cinntra.com"),
("Zyple Software Solutions","Mumbai","Mumbai (ERP)","SAP Business One partner for SMEs","MED","zyplesoft.com"),
("SoftCore Solutions","Mumbai","Mumbai (ERP)","SAP Business One partner","MED","softwaresuggest.com"),
("KAEM Technologies","Mumbai","Mumbai (ERP)","SAP partner","MED","softwaresuggest.com"),
# --- Gaming / AdTech
("Sportz Interactive","Mumbai","Mumbai (gaming)","Sports data platforms and gamification","MED","juegostudio.com"),
("GameEon Studios","Mumbai","Mumbai (gaming)","Game development (since 2013)","MED","juegostudio.com"),
("Nilee Games and Future Technologies","Mumbai (HQ)","Mumbai (gaming)","Game and technology services","MED","juegostudio.com"),
("Motion Work Studios","Mumbai","Mumbai (gaming)","Animation, VR, mobile game development","MED","builtinmumbai.in"),
("Mobavenue","Mumbai","Mumbai (adtech)","Mobile adtech platform","MED","tracxn.com"),
("Vertoz Advertising Ltd","Mumbai","Mumbai (adtech)","Programmatic adtech, cloud infra","MED","tracxn.com"),
("POKKT","Mumbai","Mumbai (adtech)","In-game and rewarded video advertising","MED","tracxn.com"),
("Komli Media","Mumbai","Mumbai (adtech)","Digital advertising technology","LOW","tracxn.com"),
("mCanvas","Mumbai","Mumbai (adtech)","Storytelling ad formats","MED","tracxn.com"),
("Inuxu Digital Media Technologies (Adgebra)","Mumbai","Mumbai (adtech)","Omni-channel adtech platform","MED","builtinmumbai.in"),
# --- GCC / BFSI technology centres
("Morgan Stanley (Mumbai technology centre)","Mumbai","Mumbai (GCC)","Trading systems, global finance technology","MED","flexiple.com; zinnov.com"),
("JPMorgan Chase (Mumbai + Goregaon NKP)","Mumbai / Nirlon Knowledge Park, Goregaon East","Goregaon/Malad","Banking technology, Java, data platforms","MED","flexiple.com; myhq.in"),
("Citi (Mumbai technology centre)","Mumbai / Nirlon Knowledge Park, Goregaon East","Goregaon/Malad","Banking technology, regulatory reporting","MED","flexiple.com; myhq.in"),
("Standard Chartered GBS","Mumbai","Mumbai (GCC)","Banking technology and operations","MED","flexiple.com"),
("Barclays (Mumbai technology centre)","Mumbai / Nirlon Knowledge Park, Goregaon East","Goregaon/Malad","Banking technology, engineering","MED","flexiple.com; myhq.in"),
("MUFG (Mumbai GCC)","Mumbai","Mumbai (GCC)","Banking technology","MED","flexiple.com"),
("Marsh India","Mumbai","Mumbai (GCC)","Insurance analytics and technology","MED","gccjournal.in"),
("Mercer India","Mumbai","Mumbai (GCC)","HR analytics and technology","MED","gccjournal.in"),
("Guy Carpenter India","Mumbai","Mumbai (GCC)","Reinsurance analytics and technology","MED","gccjournal.in"),
("BMS Group (Mumbai GCC)","Mumbai","Mumbai (GCC)","Data, analytics and AI centre","MED","gccjournal.in"),
("Oracle India","Nirlon Knowledge Park, Goregaon East","Goregaon/Malad","Cloud, database, enterprise applications","MED","myhq.in; getsethome.com"),
("EY GDS India","Nirlon Knowledge Park, Goregaon East","Goregaon/Malad","Technology consulting, data","MED","myhq.in"),
("Firstsource Solutions","Mindspace Malad","Goregaon/Malad","BPM with technology and automation teams","MED","en.wikipedia.org"),
("L&T Infotech (LTIMindtree Mumbai)","Mindspace Malad","Goregaon/Malad","IT services","MED","en.wikipedia.org"),
("Capgemini (Mindspace Malad)","Mindspace Malad","Goregaon/Malad","IT services, application development","MED","en.wikipedia.org"),
("Accenture (Mindspace Malad)","Mindspace Malad","Goregaon/Malad","IT services, consulting","MED","en.wikipedia.org"),
("DXC Technology (formerly CSC)","Mumbai","Mumbai (services)","Digital solutions and consulting","MED","builtinmumbai.in"),
# --- Active intern hirers seen on listings
("Medius Technologies Pvt Ltd","Mumbai","Mumbai (intern hirer)","Software services; among most active Mumbai intern recruiters","MED","internshala.com"),
("BNM Business Solutions LLP","Mumbai","Mumbai (intern hirer)","Business/IT services; active intern recruiter","MED","internshala.com"),
("Break The Code","Mumbai","Mumbai (intern hirer)","Software training and development; active intern recruiter","MED","internshala.com"),
("Mple AI","Mumbai","Mumbai (intern hirer)","AI product; full-stack developer internship advertised","MED","internshala.com listing"),
("Host360","Mumbai","Mumbai (intern hirer)","Backend development internship advertised (stipend up to 12k/month)","MED","internshala.com listing"),
("Talent Corner HR Services","Mumbai","Mumbai (intern hirer)","HR services; among most active Mumbai intern recruiters","MED","internshala.com"),
]
